### ISSUE TITLE
It will only  backup to internal storage.

### ISSUE THREAD

**Issue by tazer4** [Magisk-Modules-Alt-Repo/data_backup#2]
So I'm trying to run this on my Moto G Power 2020 running Android 10 Lineage OS and it seems it doesnt not detect neither my external sdcard nor any drive I plug under OTG (exfat).  I've tried several times using the command trying to set a path to my external sd but it always says it doesn't recognize the path even thought ive cd into it.  I tried through shell on computer and on the phone terminal.

I simply don't have the free space on my internal storage for the backups, nowhere near.  Any ideas how I can get it done?  Thanks.

**Comment by ziandzivan** [comment]
I hope your external sdcard normally detected from system by a File manager for example. If so, mount extSD and/or USB-OTG and run a terminal command  :

`cp /proc/mounts /sdcard/mounts.txt`

In the root of the internal SD there will be a file mounts.txt. I need to see what this file shows. Thanks

**Comment by ziandzivan** [comment]
> Sorry for the delay here it is: https://gist.github.com/tazer4/4b029b59d08f7ecd3dfe90336cb479ac

From what I can see, your extSD is mounted. Download latest [v2.13 module](https://github.com/Magisk-Modules-Alt-Repo/data_backup/releases), install it and run data_backup.sh script. Send me a screenshot what the script shows.

> I have tried creating the 'databackup' directory

It is not necessary, the script itself creates this directory.
