### ISSUE TITLE
Support custom destination folders

### ISSUE THREAD

**Issue by okoetter** [Magisk-Modules-Alt-Repo/data_backup#4]
Please support custom destination folders. I have 60 GB free on my internal SD but this still is not enough. I would like to backup to my OTG thumb drive. So a parameter like `-d /storage/4CDC-70DD` would be nice.

**Comment by ziandzivan** [comment]
> I have 60 GB free on my internal SD but this still is not enough. I would like to backup to my OTG thumb drive.

The script supports external storage. First it is looking for mounted OTG. Read carefully "README.md": https://github.com/Magisk-Modules-Alt-Repo/data_backup#features-of-script-working 
If you have a trouble with mounting of your USB-OTG storage in your OS, make format of this storage in settings of your phone.
