### ISSUE TITLE
Save backup data directly to PC

### ISSUE THREAD

**Issue by oknchm** [Magisk-Modules-Alt-Repo/data_backup#6]
Since `data_backup` can be used with `adb` anyway (`ADB over WiFi` to be specific), is it possible to save the backup data directly to PC? I don't have enough storage available on both internal and external SD, USB-OTG is not available for me right now either. Hoping you can add this feature. Thank you!

**Comment by ziandzivan** [comment]
I am not going to make any other variants.
Buy any good storage device, for example: https://forum.xda-developers.com/t/module-discussion-data-internal-storage-backup-module-for-rooted-magisk-devices-with-twrp.4571947/#post-88529977
