### ISSUE TITLE
Restoring leaves phone encrypted.

### ISSUE THREAD

**Issue by Hallohannes123** [Magisk-Modules-Alt-Repo/data_backup#7]
(I use a Xiaomi 11T) After restoring my data, I had no screen lock. Even though all my apps and my wallpaper were present, I cant open any of them, except some core system elements like the settings app. I manually set the password to the old one again, but it doesn't fix anything. 

This exact same thing also happens when you downgrade MIUI and then your data can't be decrypted.

Is there a quick fix to get this working? Did I do anything wrong? Otherwise I would really appreciate it if you find a fix for this.

**Comment by ziandzivan** [comment]
I think the best way to put anything about restoring is here: https://github.com/ziandzivan/data_restore

>After restoring my data, I had no screen lock. Even though all my apps and my wallpaper were present, I cant open any of >them, except some core system elements like the settings app. I manually set the password to the old one again, but it doesn't >fix anything.
>
>Is there a quick fix to get this working? Did I do anything wrong? Otherwise I would really appreciate it if you find a fix for this.

Your info doesn't help me. You should understand that the script can not be an universal for all brands and their models of the phones.
You have to just check if there is a second rebooting (with root) and if you do correct steps of the restoring: https://github.com/ziandzivan/data_restore#readme
You are lucky if everything works correctly and vice versa if not.

>This exact same thing also happens when you downgrade MIUI and then your data can't be decrypted.
Android doesn't allow any downgrade without wipe date / factory reset. With my script it is not possible to do correctly too.

**Comment by Hallohannes123** [comment]
I guess I am unlucky then, I think I followed all instructions carefully.
_(I know you can't downgrade without wiping your data, this was just to show what is preventing it from working even though all data was restored.)_
